version: '3.8'

services:
  # nexus:
  #   image: sonatype/nexus3:3.69.0-java8
  #   container_name: nexus
  #   ports:
  #     - "8081:8081"
  #   volumes:
  #     - ./scripts:/scripts
  #     - ./common/data/nexus-data:/nexus-data
  #   environment:
  #     - NEXUS_SECURITY_RANDOMPASSWORD=false
  #     - NEXUS_ADMIN_PASSWORD=admin123
  #   restart: always
  #   entrypoint: /scripts/system/before/nexus/add_proxy.sh
  #   healthcheck:
  #     test: [ "CMD-SHELL", "test -f /scripts/system/before/nexus/.lock" ]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 10
  #   networks:
  #     ambari-env-network:
  #       ipv4_address: 172.20.0.2

  nginx:
    image: centos:7.9.2009
    container_name: nginx
    hostname: nginx
    ports:
      - "86:80"
    volumes:
      - ./scripts:/scripts
      - ./common/data/rpm-package:/data/rpm-package
    restart: always
    tty: true
    privileged: true
    entrypoint: /scripts/nginx.sh
    networks:
      ambari-env-network:
        ipv4_address: 172.20.0.10
    healthcheck:
      test: [ "CMD-SHELL", "test -f /scripts/.init_nginx_done" ]
      interval: 30s
      timeout: 10s
      retries: 10

  valley1:
    image: centos:7.9.2009
    container_name: valley1
    hostname: valley1
    ports:
      - "28088:8080"
    tty: true
    privileged: true
    volumes:
      - ./scripts:/scripts
      - ./common/conf:/opt/modules/conf
      - ./common/data/mvn:/root/.m2
      - ./common/data/rpm-package:/data/rpm-package
    entrypoint: /scripts/master.sh
    depends_on:
      nginx:
        condition: service_healthy
    networks:
      ambari-env-network:
        ipv4_address: 172.20.0.11

  valley2:
    image: centos:7.9.2009
    container_name: valley2
    hostname: valley2
    tty: true
    privileged: true
    volumes:
      - ./scripts:/scripts
      - ./common/conf:/opt/modules/conf
      - ./common/data/mvn:/root/.m2
    entrypoint: /scripts/slave.sh
    depends_on:
      nginx:
        condition: service_healthy
    networks:
      ambari-env-network:
        ipv4_address: 172.20.0.12

  valley3:
    image: centos:7.9.2009
    container_name: valley3
    hostname: valley3
    tty: true
    privileged: true
    volumes:
      - ./scripts:/scripts
      - ./common/conf:/opt/modules/conf
      - ./common/data/mvn:/root/.m2
    entrypoint: /scripts/slave.sh
    depends_on:
      nginx:
        condition: service_healthy
    networks:
      ambari-env-network:
        ipv4_address: 172.20.0.13

  valley4:
    image: centos:7.9.2009
    container_name: valley4
    hostname: valley4
    tty: true
    privileged: true
    volumes:
      - ./scripts:/scripts
      - ./common/conf:/opt/modules/conf
      - ./common/data/mvn:/root/.m2
    entrypoint: /scripts/slave.sh
    depends_on:
      nginx:
        condition: service_healthy
    networks:
      ambari-env-network:
        ipv4_address: 172.20.0.14
networks:
  ambari-env-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
